# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: hdapsd.spec

# add or remove files that should be synced
files_to_sync:
    - hdapsd.spec
    - .packit.yaml

actions:
  get-current-version:
    - bash -c "grep AC_INIT configure.ac | cut -f2 -d, | tr --complement --delete '0-9'"
  create-archive:
    - ./autogen.sh
    - make dist
    - bash -c "ls -1t hdapsd-*.tar.gz | head -n 1"

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: hdapsd
# downstream (Fedora) RPM package name
downstream_package_name: hdapsd

upstream_tag_template: '{version}'

srpm_build_deps:
  - autoconf
  - automake
  - gcc
  - make

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    targets:
      - epel-9
      - epel-10
      - fedora-stable

  - <<: *copr
    job: tests

  - <<: *copr
    trigger: commit
    branch: master
    owner: evgeni
    project: linux-thinkpad-devel
