---
name: Test

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - none
          - libconfig
    steps:
      - uses: actions/checkout@v4
      - name: Install pkg-config
        run: sudo apt-get install -y pkg-config
      - name: Install libconfig
        if: matrix.config == 'libconfig'
        run: sudo apt-get install -y libconfig-dev
      - run: ./autogen.sh
      - run: make
